## Linear Algebra

In [61]:
import numpy as np

### Matrix Operation

In [62]:
A=np.array([
    [2, -1],
    [0, 3],
])    
B=np.array([
    [1, 2],
    [-3, 4],
])    
print(A+B)
print()
print(A*B)
print()
print(3*A-2*B)

[[ 3  1]
 [-3  7]]

[[ 2 -2]
 [ 0 12]]

[[ 4 -7]
 [ 6  1]]


## Determination and Inverse

In [63]:
import numpy.linalg as LA
LA.det(A)

np.float64(6.0)

## Inverse

In [64]:
LA.inv(A)

array([[0.5       , 0.16666667],
       [0.        , 0.33333333]])

## Eigen Value and Eigen vectors


In [65]:
import numpy as np

# Define the matrix
C = np.array([[4, 1],
              [-2, 1]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Print the results
print("Matrix C:")
print(A)
print("\nEigenvalue (first):")
print(eigenvalues[0])
print("\nCorresponding Eigenvector:")
print(eigenvectors[:, 0])

Matrix C:
[[ 2 -1]
 [ 0  3]]

Eigenvalue (first):
2.0

Corresponding Eigenvector:
[1. 0.]


## Car questions

In [66]:
import numpy as np
import numpy.linalg as LA

X = np.array([[4, 1.5, 100],
              [6, 2.0, 150]])
y = np.array([20, 30])

# Method 1: Using the Normal Equation: β = (X.T * X)^(-1) * X.T * y
print("Using Normal Equation: β = (X.T * X)^(-1) * X.T * y")
print()

# Compute X.T (transpose of X)
X_T = X.T
print("X.T (Transpose of X):")
print(X_T)
print()

# Compute X * X.T (2x2 matrix)
XXT = X @ X_T
print("X * X.T:")
print(XXT)
print()

# Compute (X * X.T)^(-1) (inverse)
XXT_inv = LA.inv(XXT)
print("(X * X.T)^(-1) (Inverse):")
print(XXT_inv)
print()

# Compute β = X.T * (X * X.T)^(-1) * y
beta = X_T @ XXT_inv @ y

# Predict price for Car 3: x1=8, x2=3.0, x3=200
car3_features = np.array([8, 3.0, 200])
car3_price = car3_features @ beta

print(f"Predicted price for Car 3: {car3_price:.2f}")


Using Normal Equation: β = (X.T * X)^(-1) * X.T * y

X.T (Transpose of X):
[[  4.    6. ]
 [  1.5   2. ]
 [100.  150. ]]

X * X.T:
[[10018.25 15027.  ]
 [15027.   22540.  ]]

(X * X.T)^(-1) (Inverse):
[[ 36.00638978 -24.00479233]
 [-24.00479233  16.00359425]]

Predicted price for Car 3: 40.00
